### ISSUE TITLE
怎么部署这个前端

### ISSUE THREAD

**Issue by golden-hu** [Icemap/MapServer-Front#2]
怎么部署这个前端？

**Comment by Icemap** [comment]
你好。

这个前端是使用React编写的。可以`git clone`之后，使用`npm run build`或者`yarn build`编译后，在服务器容器部署。

当然，我是建议直接配合后端使用的，在后端打成Jar的Spring Boot软件中启动后直接浏览器打开即可。

**Comment by shinyboy** [comment]
我这运行好像有个问题


C:\tmp\MapServer-Front>npm run build

> map-server@0.1.0 build C:\tmp\MapServer-Front
> react-app-rewired build --scripts-version react-scripts-ts

Creating an optimized production build...
Starting type checking and linting service...


Using 1 worker with 2048MB memory limit
ts-loader: Using typescript@2.9.2 and C:\tmp\MapServer-Front\tsconfig.json
Failed to compile.

C:\tmp\MapServer-Front\node_modules\@types\node\assert.d.ts
(2,68): error TS1144: '{' or ';' expected.

**Comment by Icemap** [comment]
这个服务有些年头了，等下我跑起来看看。

**Comment by Icemap** [comment]
@shinyboy 
我这里也运行不起来了，等下重新写一个版本吧，OK了我在这里给你说。
前端这代码过两年直接跑不起来了可还行……

**Comment by shinyboy** [comment]
感谢  😸

**Comment by Icemap** [comment]
@shinyboy OK了，试一下吧，我关issue啦。

**Comment by shinyboy** [comment]
> @shinyboy OK了，试一下吧，我关issue啦。

谢谢啦  😻
